Keras 是一个用于构建和训练深度学习模型的高阶 API。它可用于快速设计原型、高级研究和生产。

keras的3个优点： 方便用户使用、模块化和可组合、易于扩展

# 一 导入tf.keras
tensorflow2推荐使用keras构建网络，常见的神经网络都包含在keras.layer中(最新的tf.keras的版本可能和keras不同)

In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

2.2.0
2.3.0-tf


# 二 构建简单模型

## 1 模型堆叠
最常见的模型类型是层的堆叠：tf.keras.Sequential 模型

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

## 2 网络配置
tf.keras.layers中网络配置：

activation：设置层的激活函数。此参数由内置函数的名称指定，或指定为可调用对象。默认情况下，系统不会应用任何激活函数。

kernel_initializer 和 bias_initializer：创建层权重（核和偏差）的初始化方案。此参数是一个名称或可调用对象，默认为 "Glorot uniform" 初始化器。

kernel_regularizer 和 bias_regularizer：应用层权重（核和偏差）的正则化方案，例如 L1 或 L2 正则化。默认情况下，系统不会应用正则化函数。

In [4]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# 三 训练和评估
## 1 设置训练流程
构建好模型后，通过调用 compile 方法配置该模型的学习流程

In [5]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

## 2 输入Numpy数据

In [6]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 0s 17ms/step - loss: 11.7623 - categorical_accuracy: 0.0950 - val_loss: 11.4961 - val_categorical_accuracy: 0.1100
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 11.7672 - categorical_accuracy: 0.1040 - val_loss: 11.6511 - val_categorical_accuracy: 0.1050
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 12.0566 - categorical_accuracy: 0.1060 - val_loss: 12.1515 - val_categorical_accuracy: 0.0900
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 12.8721 - categorical_accuracy: 0.1070 - val_loss: 13.4141 - val_categorical_accuracy: 0.0900
Epoch 5/10
10/10 [==============================] - 0s 4ms/step - loss: 14.6468 - categorical_accuracy: 0.1070 - val_loss: 15.5993 - val_categorical_accuracy: 0.0900
Epoch 6/10
10/10 [==============================] - 0s 3ms/step - loss: 16.8423 - categorical_accuracy: 0.1070 - val_loss: 17.3673 - val_categorical_accuracy: 0.0900
Epo

## 3 tf.data输入数据

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

30/30 [==============================] - 0s 5ms/step - loss: 39.4409 - categorical_accuracy: 0.1052 - val_loss: 50.4828 - val_categorical_accuracy: 0.1146
Epoch 2/10
30/30 [==============================] - 0s 1ms/step - loss: 62.7826 - categorical_accuracy: 0.1090 - val_loss: 77.7507 - val_categorical_accuracy: 0.1042
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - loss: 92.9841 - categorical_accuracy: 0.1068 - val_loss: 112.0685 - val_categorical_accuracy: 0.1042
Epoch 4/1

## 4 评估与预测

In [11]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
# predict
result = model.predict(test_x, batch_size=32)
print(result)

32/32 [==============================] - 0s 1ms/step - loss: 371.9262 - categorical_accuracy: 0.1150
[[0.14617059 0.         0.44325683 ... 0.24743341 0.         0.07378685]
 [0.09678894 0.         0.45749015 ... 0.27065718 0.         0.08270715]
 [0.07537924 0.         0.38921562 ... 0.35300323 0.         0.06276681]
 ...
 [0.14449637 0.         0.418727   ... 0.25003332 0.         0.07910018]
 [0.1474828  0.         0.47771034 ... 0.20119177 0.         0.08346068]
 [0.13827567 0.         0.39894342 ... 0.28650755 0.         0.07677433]]


In [12]:
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)
# predict
result = model.predict(test_x, batch_size=32)
print(result)

30/30 [==============================] - 0s 1ms/step - loss: 372.8016 - categorical_accuracy: 0.1146
[[0.14617059 0.         0.44325683 ... 0.24743341 0.         0.07378685]
 [0.09678894 0.         0.45749015 ... 0.27065718 0.         0.08270715]
 [0.07537924 0.         0.38921562 ... 0.35300323 0.         0.06276681]
 ...
 [0.14449637 0.         0.418727   ... 0.25003332 0.         0.07910018]
 [0.1474828  0.         0.47771034 ... 0.20119177 0.         0.08346068]
 [0.13827567 0.         0.39894342 ... 0.28650755 0.         0.07677433]]


# 四 构建高级模型

## 1 函数式API
tf.keras.Sequential 模型是层的简单堆叠，无法表示任意模型。使用 Keras 函数式 API 可以构建复杂的模型拓扑，例如：

多输入模型，

多输出模型，

具有共享层的模型（同一层被调用多次），

具有非序列数据流的模型（例如，残差连接）。

**使用函数式 API 构建的模型具有以下特征：**

层实例可调用并返回张量。 输入张量和输出张量用于定义 tf.keras.Model 实例。 此模型的训练方式和 Sequential 模型一样。

In [13]:
input_x = tf.keras.Input(shape=(72,))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)

model = tf.keras.Model(inputs=input_x, outputs=pred)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)

Epoch 1/5
32/32 [==============================] - 0s 1ms/step - loss: 14.0922 - accuracy: 0.1040
Epoch 2/5
32/32 [==============================] - 0s 945us/step - loss: 25.6297 - accuracy: 0.1000
Epoch 3/5
32/32 [==============================] - 0s 1ms/step - loss: 53.5605 - accuracy: 0.1140
Epoch 4/5
32/32 [==============================] - 0s 947us/step - loss: 97.2078 - accuracy: 0.1070
Epoch 5/5
32/32 [==============================] - 0s 826us/step - loss: 153.7609 - accuracy: 0.1050


## 2 模型子类化
通过对 tf.keras.Model 进行子类化并定义您自己的前向传播来构建完全可自定义的模型。在 **init** 方法中创建层并将它们设置为类实例的属性。在 call 方法中定义前向传播

In [14]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.layer1 = layers.Dense(32, activation='relu')
        self.layer2 = layers.Dense(num_classes, activation='softmax')
    
    def call(self, inputs):
        h1 = self.layer1(inputs)
        out = self.layer2(h1)
        return out

    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.num_classes
        return tf.TensorShape(shape)

model = MyModel(num_classes=10)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5)

Epoch 1/5
63/63 [==============================] - 0s 1ms/step - loss: 14.7129 - accuracy: 0.1070
Epoch 2/5
63/63 [==============================] - 0s 888us/step - loss: 21.9582 - accuracy: 0.1030
Epoch 3/5
63/63 [==============================] - 0s 773us/step - loss: 29.4208 - accuracy: 0.0970
Epoch 4/5
63/63 [==============================] - 0s 750us/step - loss: 36.2437 - accuracy: 0.0940
Epoch 5/5
63/63 [==============================] - 0s 729us/step - loss: 42.8693 - accuracy: 0.0850


## 3 自定义层
通过对 tf.keras.layers.Layer 进行子类化并实现以下方法来创建自定义层：

build：创建层的权重。使用 add_weight 方法添加权重。

call：定义前向传播。

compute_output_shape：指定在给定输入形状的情况下如何计算层的输出形状。 或者，可以通过实现 get_config 方法和 from_config 类方法序列化层。

In [15]:
class MyLayer(layers.Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        shape = tf.TensorShape((input_shape[1], self.output_dim))
        self.kernel = self.add_weight(name='kernel1', shape=shape,
                                   initializer='uniform', trainable=True)
        super(MyLayer, self).build(input_shape)

    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)

    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.output_dim
        return tf.TensorShape(shape)

    def get_config(self):
        base_config = super(MyLayer, self).get_config()
        base_config['output_dim'] = self.output_dim
        return base_config

    @classmethod
    def from_config(cls, config):
        return cls(**config)

model = tf.keras.Sequential(
[
    MyLayer(10),
    layers.Activation('softmax')
])


model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5)

Epoch 1/5
63/63 [==============================] - 0s 859us/step - loss: 11.6043 - accuracy: 0.0960
Epoch 2/5
63/63 [==============================] - 0s 748us/step - loss: 11.6010 - accuracy: 0.1030
Epoch 3/5
63/63 [==============================] - 0s 680us/step - loss: 11.5981 - accuracy: 0.1000
Epoch 4/5
63/63 [==============================] - 0s 684us/step - loss: 11.5954 - accuracy: 0.0980
Epoch 5/5
63/63 [==============================] - 0s 656us/step - loss: 11.5940 - accuracy: 0.0960


## 4 回调

In [16]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs')
]
model.fit(train_x, train_y, batch_size=16, epochs=5,
         callbacks=callbacks, validation_data=(val_x, val_y))

Epoch 1/5
63/63 [==============================] - 0s 3ms/step - loss: 11.5910 - accuracy: 0.1010 - val_loss: 11.3790 - val_accuracy: 0.1000
Epoch 2/5
63/63 [==============================] - 0s 1ms/step - loss: 11.5894 - accuracy: 0.1040 - val_loss: 11.3721 - val_accuracy: 0.1000
Epoch 3/5
63/63 [==============================] - 0s 1ms/step - loss: 11.5858 - accuracy: 0.0930 - val_loss: 11.3721 - val_accuracy: 0.0950
Epoch 4/5
63/63 [==============================] - 0s 1ms/step - loss: 11.5852 - accuracy: 0.0920 - val_loss: 11.3699 - val_accuracy: 0.1000
Epoch 5/5
63/63 [==============================] - 0s 1ms/step - loss: 11.5828 - accuracy: 0.0890 - val_loss: 11.3687 - val_accuracy: 0.0950


# 五 保持和恢复
## 1 权重保存

In [18]:
model = tf.keras.Sequential([
layers.Dense(64, activation='relu'),
layers.Dense(10, activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5,
         validation_data=(val_x, val_y))

model.save_weights('./weights/model')
model.load_weights('./weights/model')
model.save_weights('./model.h5')
model.load_weights('./model.h5')

Epoch 1/5
63/63 [==============================] - 0s 2ms/step - loss: 13.7191 - accuracy: 0.0940 - val_loss: 16.8436 - val_accuracy: 0.1100
Epoch 2/5
63/63 [==============================] - 0s 1ms/step - loss: 20.6583 - accuracy: 0.0980 - val_loss: 23.7384 - val_accuracy: 0.1150
Epoch 3/5
63/63 [==============================] - 0s 1ms/step - loss: 24.6128 - accuracy: 0.0890 - val_loss: 25.6564 - val_accuracy: 0.1150
Epoch 4/5
63/63 [==============================] - 0s 1ms/step - loss: 26.2493 - accuracy: 0.1020 - val_loss: 26.8418 - val_accuracy: 0.0900
Epoch 5/5
63/63 [==============================] - 0s 1ms/step - loss: 27.5547 - accuracy: 0.1020 - val_loss: 27.9652 - val_accuracy: 0.0900


## 2 保存网络结构

In [19]:
# 序列化成json
import json
import pprint
json_str = model.to_json()
pprint.pprint(json.loads(json_str))
fresh_model = tf.keras.models.model_from_json(json_str)
# 保持为yaml格式  #需要提前安装pyyaml

yaml_str = model.to_yaml()
print(yaml_str)
fresh_model = tf.keras.models.model_from_yaml(yaml_str)

{'backend': 'tensorflow',
 'class_name': 'Sequential',
 'config': {'build_input_shape': [None, 72],
            'layers': [{'class_name': 'Dense',
                        'config': {'activation': 'relu',
                                   'activity_regularizer': None,
                                   'bias_constraint': None,
                                   'bias_initializer': {'class_name': 'Zeros',
                                                        'config': {}},
                                   'bias_regularizer': None,
                                   'dtype': 'float32',
                                   'kernel_constraint': None,
                                   'kernel_initializer': {'class_name': 'GlorotUniform',
                                                          'config': {'seed': None}},
                                   'kernel_regularizer': None,
                                   'name': 'dense_19',
                                   'trainable': Tru

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(yaml_string)


## 3 保存整个模型

In [20]:
model = tf.keras.Sequential([
  layers.Dense(10, activation='softmax', input_shape=(72,)),
  layers.Dense(10, activation='softmax')
])
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)
model.save('all_model.h5')
model = tf.keras.models.load_model('all_model.h5')

Epoch 1/5
32/32 [==============================] - 0s 916us/step - loss: 11.5952 - accuracy: 0.0950
Epoch 2/5
32/32 [==============================] - 0s 916us/step - loss: 11.6888 - accuracy: 0.1100
Epoch 3/5
32/32 [==============================] - 0s 933us/step - loss: 11.7366 - accuracy: 0.1100
Epoch 4/5
32/32 [==============================] - 0s 809us/step - loss: 11.7483 - accuracy: 0.1100
Epoch 5/5
32/32 [==============================] - 0s 742us/step - loss: 11.7518 - accuracy: 0.1100


## 六 将keras用于Estimator
Estimator API 用于针对分布式环境训练模型。它适用于一些行业使用场景，例如用大型数据集进行分布式训练并导出模型以用于生产

In [ ]:
model = tf.keras.Sequential([layers.Dense(10,activation='softmax'),
                          layers.Dense(10,activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

estimator = tf.keras.estimator.model_to_estimator(model)